server:
  port: 8080
  servlet:
    session:
      timeout: 30m # 세션 타임아웃 30분
      cookie:
        http-only: true
        secure: false # 개발 환경에서는 false, 운영 환경에서는 true

spring:
  application:
    name: zzaptalk-backend
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  
  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/zzaptalk?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update # 개발 중에는 update, 운영에서는 validate 사용
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# Logging Configuration
logging:
  level:
    com.zzaptalk.backend: DEBUG
    org.springframework.security: DEBUG